branches:
    only:
        - master
language: php
php:
    - 7.0
    - hhvm
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install nodejs phantomjs
    - phantomjs --webdriver=4444 > /dev/null &
before_script:
    - composer --no-interaction install
    - php -Slocalhost:8000 -tweb > /dev/null 2>&1 &
    - bin/console user:add admin admin
script:
    - node_modules/.bin/coffeelint -f config/ci/coffeelint.json -r resources/coffee
    - php -l src
    - bin/behat
